### ISSUE TITLE
This plugin has been marked as Obsolete

### ISSUE THREAD

**Issue by eduncan911** [cblt2l/FreeCAD-CuraEngine-Plugin#9]
@cblt2l do you have plans to updating this plugin to be compatible with the latest versions of FreeCAD?

**Comment by cblt2l** [comment]
No immediate plans to. Have thought about doing a rewrite for newer slicing engines but don't know if there is much value in a plugin these days.

**Comment by Kreyren** [comment]
@cblt2l Elaborate what is this obsolete by, thanks

**Comment by eduncan911** [comment]
> @cblt2l Elaborate what is this obsolete by, thanks

I believe the python version, like other workbenches.

**Comment by Kreyren** [comment]
> I believe the python version, like other workbenches. -- @eduncan911 (https://github.com/cblt2l/FreeCAD-CuraEngine-Plugin/issues/9#issuecomment-999219177)

What python version? Like by FreeCAD's new python version?

if so that doesn't make sense to me as `obsolete` means that better solution has been found and project's development ceased to focus on that new solution.. If the FreeCAD's python version is an issue then it should be called `outdated`.

**Comment by eduncan911** [comment]
It's just a guess... Several workbenches no longer are working/supported because FreeCAD went to Python 3.x - which is not backwards compatible with Python 2.x code.  Those older workbenches are Python 2.x.

And this workbench being 8 years old code... I seriously doubt it's Python 3.x.

The author says above that they may consider re-writing from scratch...

**Comment by mea08kw** [comment]
> No immediate plans to. Have thought about doing a rewrite for newer slicing engines but don't know if there is much value in a plugin these days.

Hi, I have tried to clone all relevent files into Mod directory, but the plug-in can not be loaded.

Error message in message box:

13:56:34  During initialization the error "inconsistent use of tabs and spaces in indentation (<string>, line 52)" occurred in C:\Program Files\FreeCAD 0.20\Mod\FreeCAD-CuraEngine-Plugin\InitGui.py
13:56:34  Please look into the log file for further information

It seems that it is caused by the updated version of FreeCAD.

I also had a look into files for different workbenches, the sytax and structure are slightly different, I'm wondering if Cura workbench will work after modifying those python files to be compatible with latest FreeCAD.

Looking forward to hearing from you.

Thanks in advance.

**Comment by eduncan911** [comment]
> No immediate plans to. Have thought about doing a rewrite for newer slicing engines but don't know if there is much value in a plugin these days.

I'll close this issue as I no longer use Cura.  Someone else can open a new issue to track any work.
